import './singlePost.css';

export default function SinglePost(){
  return(
    <div className='singlePost'>
      <div className='singlePostWrapper'>
        <img className='singlePostImg' src='https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1' alt='' />
        <h1 className='singlePostTitle'>
          hidfhsdufsdnnsdfhsifhusdfuehwufhweufhwe.
          <div className='singlePostEdit'>
            <i className="singlePostIcon fa-solid fa-user-pen"></i>
            <i className="singlePostIcon fa-solid fa-trash-can"></i>
          </div>
        </h1>
        <div className='singlePostInfo'>
          <span className='singlePostAuthor'>Autor: <b>hfsiufhsd</b></span>
          <span className='singlePostDate'>1 hour ago</span>
        </div>
        <p className='singlePostDesc'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in nisi massa. Fusce vitae ligula eget arcu faucibus faucibus. Curabitur a lectus eu tellus cursus blandit. Integer ipsum magna, suscipit et hendrerit ullamcorper, consequat non sem. Donec dignissim pharetra purus, id ullamcorper diam molestie id. Nam vel sollicitudin risus. Duis tristique lectus a sollicitudin ornare. Donec massa elit, feugiat sed mollis consequat, laoreet ac diam. Ut ut efficitur urna, id condimentum orci. Pellentesque dictum risus eget sapien maximus tincidunt. Vivamus et sem vel nisl vulputate lobortis at id libero. Sed malesuada velit non gravida eleifend. Donec congue purus ac ligula vestibulum venenatis. Sed id finibus ex. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Pellentesque dictum tempus sagittis. Praesent eget turpis massa. Suspendisse non massa vitae velit mollis blandit. Integer ac turpis sed leo vulputate rutrum rhoncus a leo. In dictum finibus tempor. Fusce sit amet imperdiet arcu, sed imperdiet leo. Integer ac arcu et lectus pellentesque blandit id ac quam. Nunc ac massa libero. Maecenas semper ante a quam efficitur convallis. Proin risus nulla, aliquet vitae erat ac, eleifend vehicula felis. Nulla consectetur venenatis dictum. Mauris dignissim sem libero, nec posuere justo bibendum ut. Nunc fringilla, magna a fermentum blandit, lectus leo bibendum eros, nec sodales tellus magna sed nisi. Sed a arcu odio. Integer bibendum elementum vehicula. Donec nunc dui, vehicula vitae feugiat blandit, porttitor sit amet nisi.

Fusce at euismod nulla. Pellentesque nec urna at nisl blandit lobortis eu vitae felis. Integer ut purus elementum, ultricies purus sit amet, ullamcorper neque. Nam eget rutrum quam. Donec malesuada ac tellus quis imperdiet. Vivamus in felis quis nisi viverra varius eget nec eros. Quisque non lorem magna. Curabitur ac purus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tristique fringilla magna, ut varius diam. Pellentesque vel tincidunt arcu. Vivamus eget convallis diam.

Duis velit quam, imperdiet ut ullamcorper sit amet, ultricies molestie quam. Quisque non consectetur diam. Vestibulum tempus mattis dolor, a feugiat quam tincidunt eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer congue eros tellus, id egestas sem sagittis quis. Pellentesque sit amet varius velit. Quisque eu purus ipsum.

Proin dictum viverra lorem ut consequat. Sed suscipit, purus non ullamcorper efficitur, lectus nunc faucibus lectus, sit amet dignissim sapien libero in quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ex nulla, pharetra a neque nec, ultrices efficitur leo. Ut pharetra luctus ligula, ac dictum eros. Phasellus dictum viverra nisi vel rhoncus. Phasellus ac libero non justo imperdiet congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et quam velit. Nunc at congue erat. Vestibulum maximus justo at felis hendrerit, sit amet commodo mi fermentum. Mauris laoreet, lectus sed sagittis condimentum, nibh odio volutpat lorem, non pharetra dui nisi eu nisl. Integer urna mauris, placerat et felis nec, gravida semper nisi. Sed lacinia nulla vel fermentum efficitur. Donec cursus diam quam, eget tristique urna viverra et. Proin non sodales eros.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in nisi massa. Fusce vitae ligula eget arcu faucibus faucibus. Curabitur a lectus eu tellus cursus blandit. Integer ipsum magna, suscipit et hendrerit ullamcorper, consequat non sem. Donec dignissim pharetra purus, id ullamcorper diam molestie id. Nam vel sollicitudin risus. Duis tristique lectus a sollicitudin ornare. Donec massa elit, feugiat sed mollis consequat, laoreet ac diam. Ut ut efficitur urna, id condimentum orci. Pellentesque dictum risus eget sapien maximus tincidunt. Vivamus et sem vel nisl vulputate lobortis at id libero. Sed malesuada velit non gravida eleifend. Donec congue purus ac ligula vestibulum venenatis. Sed id finibus ex. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Pellentesque dictum tempus sagittis. Praesent eget turpis massa. Suspendisse non massa vitae velit mollis blandit. Integer ac turpis sed leo vulputate rutrum rhoncus a leo. In dictum finibus tempor. Fusce sit amet imperdiet arcu, sed imperdiet leo. Integer ac arcu et lectus pellentesque blandit id ac quam. Nunc ac massa libero. Maecenas semper ante a quam efficitur convallis. Proin risus nulla, aliquet vitae erat ac, eleifend vehicula felis. Nulla consectetur venenatis dictum. Mauris dignissim sem libero, nec posuere justo bibendum ut. Nunc fringilla, magna a fermentum blandit, lectus leo bibendum eros, nec sodales tellus magna sed nisi. Sed a arcu odio. Integer bibendum elementum vehicula. Donec nunc dui, vehicula vitae feugiat blandit, porttitor sit amet nisi.

Fusce at euismod nulla. Pellentesque nec urna at nisl blandit lobortis eu vitae felis. Integer ut purus elementum, ultricies purus sit amet, ullamcorper neque. Nam eget rutrum quam. Donec malesuada ac tellus quis imperdiet. Vivamus in felis quis nisi viverra varius eget nec eros. Quisque non lorem magna. Curabitur ac purus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tristique fringilla magna, ut varius diam. Pellentesque vel tincidunt arcu. Vivamus eget convallis diam.

Duis velit quam, imperdiet ut ullamcorper sit amet, ultricies molestie quam. Quisque non consectetur diam. Vestibulum tempus mattis dolor, a feugiat quam tincidunt eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer congue eros tellus, id egestas sem sagittis quis. Pellentesque sit amet varius velit. Quisque eu purus ipsum.

Proin dictum viverra lorem ut consequat. Sed suscipit, purus non ullamcorper efficitur, lectus nunc faucibus lectus, sit amet dignissim sapien libero in quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ex nulla, pharetra a neque nec, ultrices efficitur leo. Ut pharetra luctus ligula, ac dictum eros. Phasellus dictum viverra nisi vel rhoncus. Phasellus ac libero non justo imperdiet congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et quam velit. Nunc at congue erat. Vestibulum maximus justo at felis hendrerit, sit amet commodo mi fermentum. Mauris laoreet, lectus sed sagittis condimentum, nibh odio volutpat lorem, non pharetra dui nisi eu nisl. Integer urna mauris, placerat et felis nec, gravida semper nisi. Sed lacinia nulla vel fermentum efficitur. Donec cursus diam quam, eget tristique urna viverra et. Proin non sodales eros.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in nisi massa. Fusce vitae ligula eget arcu faucibus faucibus. Curabitur a lectus eu tellus cursus blandit. Integer ipsum magna, suscipit et hendrerit ullamcorper, consequat non sem. Donec dignissim pharetra purus, id ullamcorper diam molestie id. Nam vel sollicitudin risus. Duis tristique lectus a sollicitudin ornare. Donec massa elit, feugiat sed mollis consequat, laoreet ac diam. Ut ut efficitur urna, id condimentum orci. Pellentesque dictum risus eget sapien maximus tincidunt. Vivamus et sem vel nisl vulputate lobortis at id libero. Sed malesuada velit non gravida eleifend. Donec congue purus ac ligula vestibulum venenatis. Sed id finibus ex. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Pellentesque dictum tempus sagittis. Praesent eget turpis massa. Suspendisse non massa vitae velit mollis blandit. Integer ac turpis sed leo vulputate rutrum rhoncus a leo. In dictum finibus tempor. Fusce sit amet imperdiet arcu, sed imperdiet leo. Integer ac arcu et lectus pellentesque blandit id ac quam. Nunc ac massa libero. Maecenas semper ante a quam efficitur convallis. Proin risus nulla, aliquet vitae erat ac, eleifend vehicula felis. Nulla consectetur venenatis dictum. Mauris dignissim sem libero, nec posuere justo bibendum ut. Nunc fringilla, magna a fermentum blandit, lectus leo bibendum eros, nec sodales tellus magna sed nisi. Sed a arcu odio. Integer bibendum elementum vehicula. Donec nunc dui, vehicula vitae feugiat blandit, porttitor sit amet nisi.

Fusce at euismod nulla. Pellentesque nec urna at nisl blandit lobortis eu vitae felis. Integer ut purus elementum, ultricies purus sit amet, ullamcorper neque. Nam eget rutrum quam. Donec malesuada ac tellus quis imperdiet. Vivamus in felis quis nisi viverra varius eget nec eros. Quisque non lorem magna. Curabitur ac purus tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer tristique fringilla magna, ut varius diam. Pellentesque vel tincidunt arcu. Vivamus eget convallis diam.

Duis velit quam, imperdiet ut ullamcorper sit amet, ultricies molestie quam. Quisque non consectetur diam. Vestibulum tempus mattis dolor, a feugiat quam tincidunt eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer congue eros tellus, id egestas sem sagittis quis. Pellentesque sit amet varius velit. Quisque eu purus ipsum.

Proin dictum viverra lorem ut consequat. Sed suscipit, purus non ullamcorper efficitur, lectus nunc faucibus lectus, sit amet dignissim sapien libero in quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ex nulla, pharetra a neque nec, ultrices efficitur leo. Ut pharetra luctus ligula, ac dictum eros. Phasellus dictum viverra nisi vel rhoncus. Phasellus ac libero non justo imperdiet congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum et quam velit. Nunc at congue erat. Vestibulum maximus justo at felis hendrerit, sit amet commodo mi fermentum. Mauris laoreet, lectus sed sagittis condimentum, nibh odio volutpat lorem, non pharetra dui nisi eu nisl. Integer urna mauris, placerat et felis nec, gravida semper nisi. Sed lacinia nulla vel fermentum efficitur. Donec cursus diam quam, eget tristique urna viverra et. Proin non sodales eros.</p>
      </div>
    </div>
  )
}